In [1]:
#libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import os

In [3]:
#read Dataset
df=pd.read_csv('E:\\python for data science\\practical machine learning\\archive\\spam detection dataset\\spam_mail_data.csv')

In [4]:
#check if the data was uploaded
df.head(10)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
5     spam  FreeMsg Hey there darling it's been 3 week's n...
6      ham  Even my brother is not like to speak with me. ...
7      ham  As per your request 'Melle Melle (Oru Minnamin...
8     spam  WINNER!! As a valued network customer you have...
9     spam  Had your mobile 11 months or more? U R entitle...

In [5]:
df.groupby('Category').describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [6]:
df['spam']=df['Category'].apply(lambda x:1 if x=='spam' else 0)

In [7]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
#convert Message column to a numericat values using
# CountVectorizer Technique
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(df.Message, df.spam,  test_size=0.2)

In [9]:
from sklearn.feature_extraction.text import CountVectorizer

In [10]:
vec=CountVectorizer()

In [11]:
x_train_count=vec.fit_transform(x_train.values)
x_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [12]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(x_train_count, y_train)

MultinomialNB()

In [13]:
#calculate the score of the model , here we'll convert the x_test into a count
x_test_count = vec.transform(x_test)
model.score(x_test_count, y_test)

0.9865470852017937

In [14]:
#test the model 
sample =[ 'Ahhh. Work. I vaguely remember that! What does it feel like? Lol']
# here we'll convert that e-mail into a countVectorizer
sample_count = vec.transform(sample)
model.predict(sample_count)

array([0], dtype=int64)

In [15]:
#this sample is a spam , lets see that on the model
spam_test = ['Congrats! 1 year special cinema pass for 2 is yours. call 09061209465 now! C Suprman V, Matrix3, StarWars3, etc all 4 FREE! bx420-ip4-5we. 150pm. Dont miss out!']
spam_test_count = vec.transform(spam_test)
model.predict(spam_test_count)

array([1], dtype=int64)

In [16]:
#that's all , now let's save the model
import pickle
with open ('Spam Detectoon','wb') as f:
    pickle.dump(model, f)
